-- Keep existing primary keys and relations intact. Public IDs are the opaque API/UI identity.
ALTER TABLE `organizations` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `users` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `workspaces` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `workspace_members` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `projects` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `project_members` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `tasks` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `task_dependencies` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `task_tags` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `task_tag_assignments` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `task_followers` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `comments` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `comment_mentions` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `activity_logs` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `notifications` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `attachments` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `permissions` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `roles` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `workspace_invitations` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `role_permissions` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `email_verification_tokens` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `email_otp_verifications` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `password_resets` ADD COLUMN `public_id` VARCHAR(40) NULL;
ALTER TABLE `sessions` ADD COLUMN `public_id` VARCHAR(40) NULL;

UPDATE `organizations` SET `public_id` = CONCAT('org_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `users` SET `public_id` = CONCAT('usr_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `workspaces` SET `public_id` = CONCAT('wsp_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `workspace_members` SET `public_id` = CONCAT('wmb_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `projects` SET `public_id` = CONCAT('prj_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `project_members` SET `public_id` = CONCAT('pmb_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `tasks` SET `public_id` = CONCAT('tsk_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `task_dependencies` SET `public_id` = CONCAT('tdp_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `task_tags` SET `public_id` = CONCAT('tag_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `task_tag_assignments` SET `public_id` = CONCAT('tta_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `task_followers` SET `public_id` = CONCAT('tfl_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `comments` SET `public_id` = CONCAT('cmt_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `comment_mentions` SET `public_id` = CONCAT('cmn_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `activity_logs` SET `public_id` = CONCAT('act_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `notifications` SET `public_id` = CONCAT('ntf_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `attachments` SET `public_id` = CONCAT('att_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `permissions` SET `public_id` = CONCAT('per_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `roles` SET `public_id` = CONCAT('rol_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `workspace_invitations` SET `public_id` = CONCAT('win_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `role_permissions` SET `public_id` = CONCAT('rpe_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `email_verification_tokens` SET `public_id` = CONCAT('evt_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `email_otp_verifications` SET `public_id` = CONCAT('eov_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `password_resets` SET `public_id` = CONCAT('pwr_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;
UPDATE `sessions` SET `public_id` = CONCAT('ses_', REPLACE(UUID(), '-', '')) WHERE `public_id` IS NULL;

ALTER TABLE `organizations` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `organizations_public_id_key` (`public_id`);
ALTER TABLE `users` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `users_public_id_key` (`public_id`);
ALTER TABLE `workspaces` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `workspaces_public_id_key` (`public_id`);
ALTER TABLE `workspace_members` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `workspace_members_public_id_key` (`public_id`);
ALTER TABLE `projects` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `projects_public_id_key` (`public_id`);
ALTER TABLE `project_members` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `project_members_public_id_key` (`public_id`);
ALTER TABLE `tasks` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `tasks_public_id_key` (`public_id`);
ALTER TABLE `task_dependencies` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `task_dependencies_public_id_key` (`public_id`);
ALTER TABLE `task_tags` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `task_tags_public_id_key` (`public_id`);
ALTER TABLE `task_tag_assignments` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `task_tag_assignments_public_id_key` (`public_id`);
ALTER TABLE `task_followers` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `task_followers_public_id_key` (`public_id`);
ALTER TABLE `comments` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `comments_public_id_key` (`public_id`);
ALTER TABLE `comment_mentions` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `comment_mentions_public_id_key` (`public_id`);
ALTER TABLE `activity_logs` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `activity_logs_public_id_key` (`public_id`);
ALTER TABLE `notifications` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `notifications_public_id_key` (`public_id`);
ALTER TABLE `attachments` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `attachments_public_id_key` (`public_id`);
ALTER TABLE `permissions` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `permissions_public_id_key` (`public_id`);
ALTER TABLE `roles` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `roles_public_id_key` (`public_id`);
ALTER TABLE `workspace_invitations` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `workspace_invitations_public_id_key` (`public_id`);
ALTER TABLE `role_permissions` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `role_permissions_public_id_key` (`public_id`);
ALTER TABLE `email_verification_tokens` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `email_verification_tokens_public_id_key` (`public_id`);
ALTER TABLE `email_otp_verifications` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `email_otp_verifications_public_id_key` (`public_id`);
ALTER TABLE `password_resets` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `password_resets_public_id_key` (`public_id`);
ALTER TABLE `sessions` MODIFY `public_id` VARCHAR(40) NOT NULL, ADD UNIQUE INDEX `sessions_public_id_key` (`public_id`);
